/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
    }
    interface SAbdullakhCardDesign {
        "cardDesign": any;
    }
    interface SAbdullakhClauseMatch {
        "clauseMatch": any;
    }
    interface SAbdullakhClauseMatchContent {
        "clauseMatch": any;
    }
    interface SAbdullakhExpenseManagement {
        /**
          * массив personalSecurity
         */
        "expenseManagement": any;
        /**
          * массив personalSecurity
         */
        "expenseManagementImg": string;
    }
    interface SAbdullakhExploreFeatures {
        "exploreFeatures": any;
    }
    interface SAbdullakhExploreFeaturesBlocks {
        "arr": any;
    }
    interface SAbdullakhFooter {
        "footer": any[];
    }
    interface SAbdullakhFooterLogoBlocks {
        "arr": any;
    }
    interface SAbdullakhFooterMenuBlocks {
        "arr": any;
    }
    interface SAbdullakhFooterMenuLinks {
        "arr": any;
    }
    interface SAbdullakhHeadMenu {
        /**
          * массив меню
         */
        "headNav": any[];
        /**
          * массив меню
         */
        "headText": any;
    }
    interface SAbdullakhHeadMenuInPopup {
        /**
          * массив меню в popup
         */
        "arr": any;
    }
    interface SAbdullakhHeadMenuPopup {
        /**
          * массив меню в popup
         */
        "arr": any;
    }
    interface SAbdullakhHeadNavEnd {
        /**
          * массив меню
         */
        "headText": any;
    }
    interface SAbdullakhHeadNavStart {
        /**
          * массив меню
         */
        "headText": any;
    }
    interface SAbdullakhHeader {
        /**
          * массив меню
         */
        "headNav": any[];
        /**
          * массив меню
         */
        "headText": any;
    }
    interface SAbdullakhIcons {
        "arr": any;
    }
    interface SAbdullakhIconsBlock {
        /**
          * props принятия данных для компонента SAbdullakhIconsBlock
         */
        "previewBackground": any;
    }
    interface SAbdullakhLinkBlock {
        "linkBlock": any;
    }
    interface SAbdullakhListBlock {
        /**
          * массив ListBlock
         */
        "arr": any;
    }
    interface SAbdullakhMultiCurrencySlaider {
        "multiCurrencySlaider": string;
    }
    interface SAbdullakhOtherFeatures {
        "featuresblock": any;
        "otherFeatures": any;
    }
    interface SAbdullakhOtherFeaturesBlocks {
        "arr": any;
    }
    interface SAbdullakhPersonalSecurity {
        /**
          * массив personalSecurity
         */
        "personalSecurity": any;
        /**
          * путь к img personalSecurity
         */
        "personalSecurityImg": string;
    }
    interface SAbdullakhPreHeader {
    }
    interface SAbdullakhProductPresentation {
        /**
          * массив элементов productPresentation
         */
        "productPresentation": any;
    }
    interface SAbdullakhProductPresentationContent {
        /**
          * массив элементов product-presentation-conten
         */
        "arr": any;
        /**
          * массив элементов product-presentation-conten
         */
        "videoScr": string;
    }
    interface SAbdullakhProductPresentationVideo {
        /**
          * массив элементов productPresentation
         */
        "videoScr": any;
    }
    interface SAbdullakhSecurityControl {
        /**
          * массив personalSecurity
         */
        "securityControl": any;
        /**
          * массив personalSecurity
         */
        "securityControlImg": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLSAbdullakhCardDesignElement extends Components.SAbdullakhCardDesign, HTMLStencilElement {
    }
    var HTMLSAbdullakhCardDesignElement: {
        prototype: HTMLSAbdullakhCardDesignElement;
        new (): HTMLSAbdullakhCardDesignElement;
    };
    interface HTMLSAbdullakhClauseMatchElement extends Components.SAbdullakhClauseMatch, HTMLStencilElement {
    }
    var HTMLSAbdullakhClauseMatchElement: {
        prototype: HTMLSAbdullakhClauseMatchElement;
        new (): HTMLSAbdullakhClauseMatchElement;
    };
    interface HTMLSAbdullakhClauseMatchContentElement extends Components.SAbdullakhClauseMatchContent, HTMLStencilElement {
    }
    var HTMLSAbdullakhClauseMatchContentElement: {
        prototype: HTMLSAbdullakhClauseMatchContentElement;
        new (): HTMLSAbdullakhClauseMatchContentElement;
    };
    interface HTMLSAbdullakhExpenseManagementElement extends Components.SAbdullakhExpenseManagement, HTMLStencilElement {
    }
    var HTMLSAbdullakhExpenseManagementElement: {
        prototype: HTMLSAbdullakhExpenseManagementElement;
        new (): HTMLSAbdullakhExpenseManagementElement;
    };
    interface HTMLSAbdullakhExploreFeaturesElement extends Components.SAbdullakhExploreFeatures, HTMLStencilElement {
    }
    var HTMLSAbdullakhExploreFeaturesElement: {
        prototype: HTMLSAbdullakhExploreFeaturesElement;
        new (): HTMLSAbdullakhExploreFeaturesElement;
    };
    interface HTMLSAbdullakhExploreFeaturesBlocksElement extends Components.SAbdullakhExploreFeaturesBlocks, HTMLStencilElement {
    }
    var HTMLSAbdullakhExploreFeaturesBlocksElement: {
        prototype: HTMLSAbdullakhExploreFeaturesBlocksElement;
        new (): HTMLSAbdullakhExploreFeaturesBlocksElement;
    };
    interface HTMLSAbdullakhFooterElement extends Components.SAbdullakhFooter, HTMLStencilElement {
    }
    var HTMLSAbdullakhFooterElement: {
        prototype: HTMLSAbdullakhFooterElement;
        new (): HTMLSAbdullakhFooterElement;
    };
    interface HTMLSAbdullakhFooterLogoBlocksElement extends Components.SAbdullakhFooterLogoBlocks, HTMLStencilElement {
    }
    var HTMLSAbdullakhFooterLogoBlocksElement: {
        prototype: HTMLSAbdullakhFooterLogoBlocksElement;
        new (): HTMLSAbdullakhFooterLogoBlocksElement;
    };
    interface HTMLSAbdullakhFooterMenuBlocksElement extends Components.SAbdullakhFooterMenuBlocks, HTMLStencilElement {
    }
    var HTMLSAbdullakhFooterMenuBlocksElement: {
        prototype: HTMLSAbdullakhFooterMenuBlocksElement;
        new (): HTMLSAbdullakhFooterMenuBlocksElement;
    };
    interface HTMLSAbdullakhFooterMenuLinksElement extends Components.SAbdullakhFooterMenuLinks, HTMLStencilElement {
    }
    var HTMLSAbdullakhFooterMenuLinksElement: {
        prototype: HTMLSAbdullakhFooterMenuLinksElement;
        new (): HTMLSAbdullakhFooterMenuLinksElement;
    };
    interface HTMLSAbdullakhHeadMenuElement extends Components.SAbdullakhHeadMenu, HTMLStencilElement {
    }
    var HTMLSAbdullakhHeadMenuElement: {
        prototype: HTMLSAbdullakhHeadMenuElement;
        new (): HTMLSAbdullakhHeadMenuElement;
    };
    interface HTMLSAbdullakhHeadMenuInPopupElement extends Components.SAbdullakhHeadMenuInPopup, HTMLStencilElement {
    }
    var HTMLSAbdullakhHeadMenuInPopupElement: {
        prototype: HTMLSAbdullakhHeadMenuInPopupElement;
        new (): HTMLSAbdullakhHeadMenuInPopupElement;
    };
    interface HTMLSAbdullakhHeadMenuPopupElement extends Components.SAbdullakhHeadMenuPopup, HTMLStencilElement {
    }
    var HTMLSAbdullakhHeadMenuPopupElement: {
        prototype: HTMLSAbdullakhHeadMenuPopupElement;
        new (): HTMLSAbdullakhHeadMenuPopupElement;
    };
    interface HTMLSAbdullakhHeadNavEndElement extends Components.SAbdullakhHeadNavEnd, HTMLStencilElement {
    }
    var HTMLSAbdullakhHeadNavEndElement: {
        prototype: HTMLSAbdullakhHeadNavEndElement;
        new (): HTMLSAbdullakhHeadNavEndElement;
    };
    interface HTMLSAbdullakhHeadNavStartElement extends Components.SAbdullakhHeadNavStart, HTMLStencilElement {
    }
    var HTMLSAbdullakhHeadNavStartElement: {
        prototype: HTMLSAbdullakhHeadNavStartElement;
        new (): HTMLSAbdullakhHeadNavStartElement;
    };
    interface HTMLSAbdullakhHeaderElement extends Components.SAbdullakhHeader, HTMLStencilElement {
    }
    var HTMLSAbdullakhHeaderElement: {
        prototype: HTMLSAbdullakhHeaderElement;
        new (): HTMLSAbdullakhHeaderElement;
    };
    interface HTMLSAbdullakhIconsElement extends Components.SAbdullakhIcons, HTMLStencilElement {
    }
    var HTMLSAbdullakhIconsElement: {
        prototype: HTMLSAbdullakhIconsElement;
        new (): HTMLSAbdullakhIconsElement;
    };
    interface HTMLSAbdullakhIconsBlockElement extends Components.SAbdullakhIconsBlock, HTMLStencilElement {
    }
    var HTMLSAbdullakhIconsBlockElement: {
        prototype: HTMLSAbdullakhIconsBlockElement;
        new (): HTMLSAbdullakhIconsBlockElement;
    };
    interface HTMLSAbdullakhLinkBlockElement extends Components.SAbdullakhLinkBlock, HTMLStencilElement {
    }
    var HTMLSAbdullakhLinkBlockElement: {
        prototype: HTMLSAbdullakhLinkBlockElement;
        new (): HTMLSAbdullakhLinkBlockElement;
    };
    interface HTMLSAbdullakhListBlockElement extends Components.SAbdullakhListBlock, HTMLStencilElement {
    }
    var HTMLSAbdullakhListBlockElement: {
        prototype: HTMLSAbdullakhListBlockElement;
        new (): HTMLSAbdullakhListBlockElement;
    };
    interface HTMLSAbdullakhMultiCurrencySlaiderElement extends Components.SAbdullakhMultiCurrencySlaider, HTMLStencilElement {
    }
    var HTMLSAbdullakhMultiCurrencySlaiderElement: {
        prototype: HTMLSAbdullakhMultiCurrencySlaiderElement;
        new (): HTMLSAbdullakhMultiCurrencySlaiderElement;
    };
    interface HTMLSAbdullakhOtherFeaturesElement extends Components.SAbdullakhOtherFeatures, HTMLStencilElement {
    }
    var HTMLSAbdullakhOtherFeaturesElement: {
        prototype: HTMLSAbdullakhOtherFeaturesElement;
        new (): HTMLSAbdullakhOtherFeaturesElement;
    };
    interface HTMLSAbdullakhOtherFeaturesBlocksElement extends Components.SAbdullakhOtherFeaturesBlocks, HTMLStencilElement {
    }
    var HTMLSAbdullakhOtherFeaturesBlocksElement: {
        prototype: HTMLSAbdullakhOtherFeaturesBlocksElement;
        new (): HTMLSAbdullakhOtherFeaturesBlocksElement;
    };
    interface HTMLSAbdullakhPersonalSecurityElement extends Components.SAbdullakhPersonalSecurity, HTMLStencilElement {
    }
    var HTMLSAbdullakhPersonalSecurityElement: {
        prototype: HTMLSAbdullakhPersonalSecurityElement;
        new (): HTMLSAbdullakhPersonalSecurityElement;
    };
    interface HTMLSAbdullakhPreHeaderElement extends Components.SAbdullakhPreHeader, HTMLStencilElement {
    }
    var HTMLSAbdullakhPreHeaderElement: {
        prototype: HTMLSAbdullakhPreHeaderElement;
        new (): HTMLSAbdullakhPreHeaderElement;
    };
    interface HTMLSAbdullakhProductPresentationElement extends Components.SAbdullakhProductPresentation, HTMLStencilElement {
    }
    var HTMLSAbdullakhProductPresentationElement: {
        prototype: HTMLSAbdullakhProductPresentationElement;
        new (): HTMLSAbdullakhProductPresentationElement;
    };
    interface HTMLSAbdullakhProductPresentationContentElement extends Components.SAbdullakhProductPresentationContent, HTMLStencilElement {
    }
    var HTMLSAbdullakhProductPresentationContentElement: {
        prototype: HTMLSAbdullakhProductPresentationContentElement;
        new (): HTMLSAbdullakhProductPresentationContentElement;
    };
    interface HTMLSAbdullakhProductPresentationVideoElement extends Components.SAbdullakhProductPresentationVideo, HTMLStencilElement {
    }
    var HTMLSAbdullakhProductPresentationVideoElement: {
        prototype: HTMLSAbdullakhProductPresentationVideoElement;
        new (): HTMLSAbdullakhProductPresentationVideoElement;
    };
    interface HTMLSAbdullakhSecurityControlElement extends Components.SAbdullakhSecurityControl, HTMLStencilElement {
    }
    var HTMLSAbdullakhSecurityControlElement: {
        prototype: HTMLSAbdullakhSecurityControlElement;
        new (): HTMLSAbdullakhSecurityControlElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "s-abdullakh-card-design": HTMLSAbdullakhCardDesignElement;
        "s-abdullakh-clause-match": HTMLSAbdullakhClauseMatchElement;
        "s-abdullakh-clause-match-content": HTMLSAbdullakhClauseMatchContentElement;
        "s-abdullakh-expense-management": HTMLSAbdullakhExpenseManagementElement;
        "s-abdullakh-explore-features": HTMLSAbdullakhExploreFeaturesElement;
        "s-abdullakh-explore-features-blocks": HTMLSAbdullakhExploreFeaturesBlocksElement;
        "s-abdullakh-footer": HTMLSAbdullakhFooterElement;
        "s-abdullakh-footer-logo-blocks": HTMLSAbdullakhFooterLogoBlocksElement;
        "s-abdullakh-footer-menu-blocks": HTMLSAbdullakhFooterMenuBlocksElement;
        "s-abdullakh-footer-menu-links": HTMLSAbdullakhFooterMenuLinksElement;
        "s-abdullakh-head-menu": HTMLSAbdullakhHeadMenuElement;
        "s-abdullakh-head-menu-in-popup": HTMLSAbdullakhHeadMenuInPopupElement;
        "s-abdullakh-head-menu-popup": HTMLSAbdullakhHeadMenuPopupElement;
        "s-abdullakh-head-nav-end": HTMLSAbdullakhHeadNavEndElement;
        "s-abdullakh-head-nav-start": HTMLSAbdullakhHeadNavStartElement;
        "s-abdullakh-header": HTMLSAbdullakhHeaderElement;
        "s-abdullakh-icons": HTMLSAbdullakhIconsElement;
        "s-abdullakh-icons-block": HTMLSAbdullakhIconsBlockElement;
        "s-abdullakh-link-block": HTMLSAbdullakhLinkBlockElement;
        "s-abdullakh-list-block": HTMLSAbdullakhListBlockElement;
        "s-abdullakh-multi-currency-slaider": HTMLSAbdullakhMultiCurrencySlaiderElement;
        "s-abdullakh-other-features": HTMLSAbdullakhOtherFeaturesElement;
        "s-abdullakh-other-features-blocks": HTMLSAbdullakhOtherFeaturesBlocksElement;
        "s-abdullakh-personal-security": HTMLSAbdullakhPersonalSecurityElement;
        "s-abdullakh-pre-header": HTMLSAbdullakhPreHeaderElement;
        "s-abdullakh-product-presentation": HTMLSAbdullakhProductPresentationElement;
        "s-abdullakh-product-presentation-content": HTMLSAbdullakhProductPresentationContentElement;
        "s-abdullakh-product-presentation-video": HTMLSAbdullakhProductPresentationVideoElement;
        "s-abdullakh-security-control": HTMLSAbdullakhSecurityControlElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
    }
    interface SAbdullakhCardDesign {
        "cardDesign"?: any;
        "onClickOnCardDesign"?: (event: CustomEvent<any>) => void;
    }
    interface SAbdullakhClauseMatch {
        "clauseMatch"?: any;
        "onClickOnClauseMatch"?: (event: CustomEvent<any>) => void;
    }
    interface SAbdullakhClauseMatchContent {
        "clauseMatch"?: any;
        "onClickOnClauseMatch"?: (event: CustomEvent<any>) => void;
    }
    interface SAbdullakhExpenseManagement {
        /**
          * массив personalSecurity
         */
        "expenseManagement"?: any;
        /**
          * массив personalSecurity
         */
        "expenseManagementImg"?: string;
        "onClickOnExpenseManagement"?: (event: CustomEvent<any>) => void;
    }
    interface SAbdullakhExploreFeatures {
        "exploreFeatures"?: any;
        /**
          * клик по в компоненте NewSinglePost
         */
        "onClickOnExploreFeature"?: (event: CustomEvent<any>) => void;
    }
    interface SAbdullakhExploreFeaturesBlocks {
        "arr"?: any;
        /**
          * клик по в компоненте NewSinglePost
         */
        "onClickOnExploreFeature"?: (event: CustomEvent<any>) => void;
    }
    interface SAbdullakhFooter {
        "footer"?: any[];
    }
    interface SAbdullakhFooterLogoBlocks {
        "arr"?: any;
    }
    interface SAbdullakhFooterMenuBlocks {
        "arr"?: any;
    }
    interface SAbdullakhFooterMenuLinks {
        "arr"?: any;
    }
    interface SAbdullakhHeadMenu {
        /**
          * массив меню
         */
        "headNav"?: any[];
        /**
          * массив меню
         */
        "headText"?: any;
        /**
          * массив меню
         */
        "onClickOnHeader"?: (event: CustomEvent<any>) => void;
    }
    interface SAbdullakhHeadMenuInPopup {
        /**
          * массив меню в popup
         */
        "arr"?: any;
        /**
          * массив меню
         */
        "onClickOnHeader"?: (event: CustomEvent<any>) => void;
    }
    interface SAbdullakhHeadMenuPopup {
        /**
          * массив меню в popup
         */
        "arr"?: any;
        /**
          * массив меню
         */
        "onClickOnHeader"?: (event: CustomEvent<any>) => void;
    }
    interface SAbdullakhHeadNavEnd {
        /**
          * массив меню
         */
        "headText"?: any;
        /**
          * массив меню
         */
        "onClickOnHeader"?: (event: CustomEvent<any>) => void;
    }
    interface SAbdullakhHeadNavStart {
        /**
          * массив меню
         */
        "headText"?: any;
        /**
          * массив меню
         */
        "onClickOnHeader"?: (event: CustomEvent<any>) => void;
    }
    interface SAbdullakhHeader {
        /**
          * массив меню
         */
        "headNav"?: any[];
        /**
          * массив меню
         */
        "headText"?: any;
        /**
          * массив меню
         */
        "onClickOnHeader"?: (event: CustomEvent<any>) => void;
    }
    interface SAbdullakhIcons {
        "arr"?: any;
    }
    interface SAbdullakhIconsBlock {
        /**
          * клик по в компоненте NewSinglePost
         */
        "onClickOnIconsBlock"?: (event: CustomEvent<any>) => void;
        /**
          * props принятия данных для компонента SAbdullakhIconsBlock
         */
        "previewBackground"?: any;
    }
    interface SAbdullakhLinkBlock {
        "linkBlock"?: any;
        /**
          * клик по в компоненте NewSinglePost
         */
        "onClickOnLinkBlock"?: (event: CustomEvent<any>) => void;
    }
    interface SAbdullakhListBlock {
        /**
          * массив ListBlock
         */
        "arr"?: any;
        "onClickOnExpenseManagement"?: (event: CustomEvent<any>) => void;
        "onClickOnPersonalSecurity"?: (event: CustomEvent<any>) => void;
    }
    interface SAbdullakhMultiCurrencySlaider {
        "multiCurrencySlaider"?: string;
    }
    interface SAbdullakhOtherFeatures {
        "featuresblock"?: any;
        /**
          * клик по в компоненте NewSinglePost
         */
        "onClickOnOtherFeatures"?: (event: CustomEvent<any>) => void;
        "otherFeatures"?: any;
    }
    interface SAbdullakhOtherFeaturesBlocks {
        "arr"?: any;
        /**
          * клик по в компоненте NewSinglePost
         */
        "onClickOnOtherFeatures"?: (event: CustomEvent<any>) => void;
    }
    interface SAbdullakhPersonalSecurity {
        /**
          * клик по элементам personalSecurity
         */
        "onClickOnPersonalSecurity"?: (event: CustomEvent<any>) => void;
        /**
          * массив personalSecurity
         */
        "personalSecurity"?: any;
        /**
          * путь к img personalSecurity
         */
        "personalSecurityImg"?: string;
    }
    interface SAbdullakhPreHeader {
        "onClose"?: (event: CustomEvent<any>) => void;
    }
    interface SAbdullakhProductPresentation {
        /**
          * клик по элементам ProductPresentation
         */
        "onClickOnProductPresentation"?: (event: CustomEvent<any>) => void;
        /**
          * массив элементов productPresentation
         */
        "productPresentation"?: any;
    }
    interface SAbdullakhProductPresentationContent {
        /**
          * массив элементов product-presentation-conten
         */
        "arr"?: any;
        /**
          * клик по элементам ProductPresentation
         */
        "onClickOnProductPresentation"?: (event: CustomEvent<any>) => void;
        /**
          * массив элементов product-presentation-conten
         */
        "videoScr"?: string;
    }
    interface SAbdullakhProductPresentationVideo {
        /**
          * клик по элементам ProductPresentation
         */
        "onClickOnProductPresentation"?: (event: CustomEvent<any>) => void;
        /**
          * массив элементов productPresentation
         */
        "videoScr"?: any;
    }
    interface SAbdullakhSecurityControl {
        "onClickOnSecurityControl"?: (event: CustomEvent<any>) => void;
        /**
          * массив personalSecurity
         */
        "securityControl"?: any;
        /**
          * массив personalSecurity
         */
        "securityControlImg"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "s-abdullakh-card-design": SAbdullakhCardDesign;
        "s-abdullakh-clause-match": SAbdullakhClauseMatch;
        "s-abdullakh-clause-match-content": SAbdullakhClauseMatchContent;
        "s-abdullakh-expense-management": SAbdullakhExpenseManagement;
        "s-abdullakh-explore-features": SAbdullakhExploreFeatures;
        "s-abdullakh-explore-features-blocks": SAbdullakhExploreFeaturesBlocks;
        "s-abdullakh-footer": SAbdullakhFooter;
        "s-abdullakh-footer-logo-blocks": SAbdullakhFooterLogoBlocks;
        "s-abdullakh-footer-menu-blocks": SAbdullakhFooterMenuBlocks;
        "s-abdullakh-footer-menu-links": SAbdullakhFooterMenuLinks;
        "s-abdullakh-head-menu": SAbdullakhHeadMenu;
        "s-abdullakh-head-menu-in-popup": SAbdullakhHeadMenuInPopup;
        "s-abdullakh-head-menu-popup": SAbdullakhHeadMenuPopup;
        "s-abdullakh-head-nav-end": SAbdullakhHeadNavEnd;
        "s-abdullakh-head-nav-start": SAbdullakhHeadNavStart;
        "s-abdullakh-header": SAbdullakhHeader;
        "s-abdullakh-icons": SAbdullakhIcons;
        "s-abdullakh-icons-block": SAbdullakhIconsBlock;
        "s-abdullakh-link-block": SAbdullakhLinkBlock;
        "s-abdullakh-list-block": SAbdullakhListBlock;
        "s-abdullakh-multi-currency-slaider": SAbdullakhMultiCurrencySlaider;
        "s-abdullakh-other-features": SAbdullakhOtherFeatures;
        "s-abdullakh-other-features-blocks": SAbdullakhOtherFeaturesBlocks;
        "s-abdullakh-personal-security": SAbdullakhPersonalSecurity;
        "s-abdullakh-pre-header": SAbdullakhPreHeader;
        "s-abdullakh-product-presentation": SAbdullakhProductPresentation;
        "s-abdullakh-product-presentation-content": SAbdullakhProductPresentationContent;
        "s-abdullakh-product-presentation-video": SAbdullakhProductPresentationVideo;
        "s-abdullakh-security-control": SAbdullakhSecurityControl;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "s-abdullakh-card-design": LocalJSX.SAbdullakhCardDesign & JSXBase.HTMLAttributes<HTMLSAbdullakhCardDesignElement>;
            "s-abdullakh-clause-match": LocalJSX.SAbdullakhClauseMatch & JSXBase.HTMLAttributes<HTMLSAbdullakhClauseMatchElement>;
            "s-abdullakh-clause-match-content": LocalJSX.SAbdullakhClauseMatchContent & JSXBase.HTMLAttributes<HTMLSAbdullakhClauseMatchContentElement>;
            "s-abdullakh-expense-management": LocalJSX.SAbdullakhExpenseManagement & JSXBase.HTMLAttributes<HTMLSAbdullakhExpenseManagementElement>;
            "s-abdullakh-explore-features": LocalJSX.SAbdullakhExploreFeatures & JSXBase.HTMLAttributes<HTMLSAbdullakhExploreFeaturesElement>;
            "s-abdullakh-explore-features-blocks": LocalJSX.SAbdullakhExploreFeaturesBlocks & JSXBase.HTMLAttributes<HTMLSAbdullakhExploreFeaturesBlocksElement>;
            "s-abdullakh-footer": LocalJSX.SAbdullakhFooter & JSXBase.HTMLAttributes<HTMLSAbdullakhFooterElement>;
            "s-abdullakh-footer-logo-blocks": LocalJSX.SAbdullakhFooterLogoBlocks & JSXBase.HTMLAttributes<HTMLSAbdullakhFooterLogoBlocksElement>;
            "s-abdullakh-footer-menu-blocks": LocalJSX.SAbdullakhFooterMenuBlocks & JSXBase.HTMLAttributes<HTMLSAbdullakhFooterMenuBlocksElement>;
            "s-abdullakh-footer-menu-links": LocalJSX.SAbdullakhFooterMenuLinks & JSXBase.HTMLAttributes<HTMLSAbdullakhFooterMenuLinksElement>;
            "s-abdullakh-head-menu": LocalJSX.SAbdullakhHeadMenu & JSXBase.HTMLAttributes<HTMLSAbdullakhHeadMenuElement>;
            "s-abdullakh-head-menu-in-popup": LocalJSX.SAbdullakhHeadMenuInPopup & JSXBase.HTMLAttributes<HTMLSAbdullakhHeadMenuInPopupElement>;
            "s-abdullakh-head-menu-popup": LocalJSX.SAbdullakhHeadMenuPopup & JSXBase.HTMLAttributes<HTMLSAbdullakhHeadMenuPopupElement>;
            "s-abdullakh-head-nav-end": LocalJSX.SAbdullakhHeadNavEnd & JSXBase.HTMLAttributes<HTMLSAbdullakhHeadNavEndElement>;
            "s-abdullakh-head-nav-start": LocalJSX.SAbdullakhHeadNavStart & JSXBase.HTMLAttributes<HTMLSAbdullakhHeadNavStartElement>;
            "s-abdullakh-header": LocalJSX.SAbdullakhHeader & JSXBase.HTMLAttributes<HTMLSAbdullakhHeaderElement>;
            "s-abdullakh-icons": LocalJSX.SAbdullakhIcons & JSXBase.HTMLAttributes<HTMLSAbdullakhIconsElement>;
            "s-abdullakh-icons-block": LocalJSX.SAbdullakhIconsBlock & JSXBase.HTMLAttributes<HTMLSAbdullakhIconsBlockElement>;
            "s-abdullakh-link-block": LocalJSX.SAbdullakhLinkBlock & JSXBase.HTMLAttributes<HTMLSAbdullakhLinkBlockElement>;
            "s-abdullakh-list-block": LocalJSX.SAbdullakhListBlock & JSXBase.HTMLAttributes<HTMLSAbdullakhListBlockElement>;
            "s-abdullakh-multi-currency-slaider": LocalJSX.SAbdullakhMultiCurrencySlaider & JSXBase.HTMLAttributes<HTMLSAbdullakhMultiCurrencySlaiderElement>;
            "s-abdullakh-other-features": LocalJSX.SAbdullakhOtherFeatures & JSXBase.HTMLAttributes<HTMLSAbdullakhOtherFeaturesElement>;
            "s-abdullakh-other-features-blocks": LocalJSX.SAbdullakhOtherFeaturesBlocks & JSXBase.HTMLAttributes<HTMLSAbdullakhOtherFeaturesBlocksElement>;
            "s-abdullakh-personal-security": LocalJSX.SAbdullakhPersonalSecurity & JSXBase.HTMLAttributes<HTMLSAbdullakhPersonalSecurityElement>;
            "s-abdullakh-pre-header": LocalJSX.SAbdullakhPreHeader & JSXBase.HTMLAttributes<HTMLSAbdullakhPreHeaderElement>;
            "s-abdullakh-product-presentation": LocalJSX.SAbdullakhProductPresentation & JSXBase.HTMLAttributes<HTMLSAbdullakhProductPresentationElement>;
            "s-abdullakh-product-presentation-content": LocalJSX.SAbdullakhProductPresentationContent & JSXBase.HTMLAttributes<HTMLSAbdullakhProductPresentationContentElement>;
            "s-abdullakh-product-presentation-video": LocalJSX.SAbdullakhProductPresentationVideo & JSXBase.HTMLAttributes<HTMLSAbdullakhProductPresentationVideoElement>;
            "s-abdullakh-security-control": LocalJSX.SAbdullakhSecurityControl & JSXBase.HTMLAttributes<HTMLSAbdullakhSecurityControlElement>;
        }
    }
}
